### ISSUE TITLE
Bad issue*/ensure* method dependencies

### ISSUE THREAD

**Issue by etj** [opengeospatial/ets-cat20-dgiwg10#37]
Test method
```
    @Test(description = "Implements A.1.4 DGIWG Transactional CSW - Ensure Update (Requirement 18)", dependsOnMethods = "issueInsertOperation")
    public void issueGetRecords_EnsureDelete() {
```

should depend on  issueDeleteOperation

**Comment by etj** [comment]
In the same way
- `issueGetRecords_EnsureUpdate` should depend on `issueUpdateOperation` not `issueInsertOperation`
- `issueDeleteOperation` should depend on `issueGetRecords_EnsureUpdate` not `issueGetRecords_EnsureInsert`

**Comment by lgoltz** [comment]
I agree with you in case of the dependencies from the tests `issueGetRecords_EnsureDelete` and `issueGetRecords_EnsureUpdate`. This is fixed with commit https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/d8d213a88613f93e2ae9a49a49bcf8c1abb78f54 on master.
@etj Can you confirm the changes?

The dependency from `issueDeleteOperation` to `issueGetRecords_EnsureInsert` is fine as the update test is not required for the delete operation.

**Comment by etj** [comment]
@lgoltz If both delete and update depend from insert, there will be no ordering between them, so delete may happen before update, and in this case the update will update 0 records and the test will fail.

**Comment by lgoltz** [comment]
Sure, you are right. Fixed with https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/c4f0be447b6dd3b9c56944fc0a402bb1aa587db2 on master.

**Comment by etj** [comment]
Verified.
Anyway, in order to test this, I used a local implementation of #29.
